In [1]:
from miniflow import  *
x,y = Input(), Input()
f = Add(x, y)
feed_dict = {x:10, y:5}

sorted_nodes = topological_sort(feed_dict)
output = forward_pass(f, sorted_nodes)
print("{} + {} = {} (according to miniflow)".format(feed_dict[x], feed_dict[y], output))

10 + 5 = 15 (according to miniflow)


In [2]:
from miniflow import *

x, y, z = Input(), Input(), Input()
f = Add(x, y, z)
feed_dict = {x:4, y: 5, z: 10}
graph = topological_sort(feed_dict)
output = forward_pass(f, graph)
print("{} + {} + {} = {}(according to miniflow)".format(feed_dict[x], feed_dict[y], feed_dict[z], output))

4 + 5 + 10 = 9(according to miniflow)


In [2]:
from miniflow import *
inputs, weights, bias = Input(), Input(), Input()
f = Linear(inputs, weights, bias)
feed_dict = {
    inputs:[6, 14, 3],
    weights:[0.5, 0.25, 1.4],
    bias:2}
graph = topological_sort(feed_dict)
output = forward_pass(f, graph)
print(output)

12.7


In [1]:
import numpy as np
from miniflow import *

X, W, b = Input(), Input(), Input()

f = Linear(X, W, b)

X_ = np.array([[-1, -2.], [-1, -2]])
W_ = np.array([[2, -3], [2, -3]])
b_ = np.array([[-3, -5]])
feed_dict = {X: X_, W: W_, b: b_}

graph = topological_sort(feed_dict)
output = forward_pass(f, graph)
print(output)

[[-9.  4.]
 [-9.  4.]]


In [2]:
import numpy as np
from miniflow import *

X, W, b = Input(), Input(), Input()

f = Linear(X, W, b)
g = Sigmoid(f)

X_ = np.array([[-1, -2], [-1, -2]])
W_ = np.array([[2, -3], [2, -3]])
b_ = np.array([-3, -5])
feed_dict = {X: X_, W: W_, b: b_}

graph = topological_sort(feed_dict)
output = forward_pass(g, graph)

print(output)

[[  1.23394576e-04   9.82013790e-01]
 [  1.23394576e-04   9.82013790e-01]]


In [2]:
import numpy as np
from miniflow import *

y, a = Input(), Input()
cost = MSE(y, a)

y_ = np.array([1, 2, 3])
a_ = np.array([4.5, 5, 10])

feed_dict = {y: y_, a: a_}
graph = topological_sort(feed_dict)

forward_pass(cost, graph)

print(cost.value)

23.4166666667


In [5]:
import random
from gd import gradient_descent_update

def f(x):
    return x**2 + 5

def df(x):
    return 2 * x

x = random.randint(0, 10000)
learning_rate = 0.001
epochs = 100

for i in range(epochs+1):
    cost = f(x)
    gradx = df(x)
    print("EPOCH{}: Cost = {:.3f}, x = {:.3f}".format(i, cost, gradx))
    x = gradient_descent_update(x, gradx, learning_rate)

EPOCH0: Cost = 1909929.000, x = 2764.000
EPOCH1: Cost = 1902296.944, x = 2758.472
EPOCH2: Cost = 1894695.385, x = 2752.955
EPOCH3: Cost = 1887124.202, x = 2747.449
EPOCH4: Cost = 1879583.274, x = 2741.954
EPOCH5: Cost = 1872072.479, x = 2736.470
EPOCH6: Cost = 1864591.698, x = 2730.997
EPOCH7: Cost = 1857140.809, x = 2725.535
EPOCH8: Cost = 1849719.694, x = 2720.084
EPOCH9: Cost = 1842328.234, x = 2714.644
EPOCH10: Cost = 1834966.311, x = 2709.215
EPOCH11: Cost = 1827633.805, x = 2703.796
EPOCH12: Cost = 1820330.601, x = 2698.389
EPOCH13: Cost = 1813056.580, x = 2692.992
EPOCH14: Cost = 1805811.626, x = 2687.606
EPOCH15: Cost = 1798595.622, x = 2682.231
EPOCH16: Cost = 1791408.454, x = 2676.866
EPOCH17: Cost = 1784250.006, x = 2671.513
EPOCH18: Cost = 1777120.163, x = 2666.170
EPOCH19: Cost = 1770018.811, x = 2660.837
EPOCH20: Cost = 1762945.836, x = 2655.516
EPOCH21: Cost = 1755901.124, x = 2650.205
EPOCH22: Cost = 1748884.563, x = 2644.904
EPOCH23: Cost = 1741896.040, x = 2639.614
EP

In [5]:
import numpy as np
from miniflow import *

X, W, b = Input(), Input(), Input()
y = Input()
f = Linear(X, W, b)
a = Sigmoid(f)
cost = MSE(y, a)

X_ = np.array([[-1., -2.], [-1, -2]])
W_ = np.array([[2.], [3.]])
b_ = np.array([-3.])
y_ = np.array([[1], [2]])


feed_dict = {X: X_, y: y_, W: W_, b: b_,}

graph = topological_sort(feed_dict)
forward_and_backward(graph)

gradients = [t.gradients[t] for t in [X, y, W, b]]

print(gradients)

None
[array([[ -3.34017280e-05,  -5.01025919e-05],
       [ -6.68040138e-05,  -1.00206021e-04]]), array([[ 0.9999833],
       [ 1.9999833]]), array([[  5.01028709e-05],
       [  1.00205742e-04]]), array([ -5.01028709e-05])]


In [2]:
import numpy as np
from miniflow import *

X, W, b = Input(), Input(), Input()

f = Linear(X, W, b)

X_ = np.array([[-1, -2.], [-1, -2]])
W_ = np.array([[2], [3]])
b_ = np.array([[-3]])
feed_dict = {X: X_, W: W_, b: b_}

graph = topological_sort(feed_dict)
output = forward_pass(f, graph)
print(output)

[[-11.]
 [-11.]]


### 波士顿房价预测

In [1]:
import numpy as np
from sklearn.datasets import load_boston
from sklearn.utils import shuffle, resample
from miniflow import *

### Load data

In [2]:
data = load_boston()
X_ = data['data']
y_ = data['target']

### Normalize data

In [3]:
X_ = (X_ - np.mean(X_, axis=0)) / np.std(X_, axis=0)

n_features = X_.shape[1]
n_hidden = 10
W1_ = np.random.randn(n_features, n_hidden)
b1_ = np.zeros(n_hidden)
W2_ = np.random.randn(n_hidden, 1)
b2_ = np.zeros(1)

### Neural network

In [4]:
X, y = Input(), Input()
W1, b1 = Input(), Input()
W2, b2 = Input(), Input()

l1 = Linear(X, W1, b1)
s1 = Sigmoid(l1)
l2 = Linear(s1, W2, b2)
cost = MSE(y, l2)

feed_dict = {
    X: X_,
    y: y_,
    W1: W1_,
    b1: b1_,
    W2: W2_,
    b2: b2_
}

epochs = 1000

#Total number of examples
m = X_.shape[0]
batch_size = 16
steps_per_epoch = m // batch_size

graph = topological_sort(feed_dict)
trainables = [W1, b1, W2, b2]

print("Total number of examples = {}".format(m)) 

Total number of examples = 506


### 训练更新

In [15]:
for i in range(epochs+1):
    loss = 0
    for j in range(steps_per_epoch):
        #step 1
        #Randomly sample a batch of examples 随机抽取一批实例
        X_batch, y_batch = resample(X_, y_, n_samples = batch_size)
        
        #Reset value of X and y Inputs
        X.value = X_batch
        y.value = y_batch
        
        #step 2
        _ = None
        forward_and_backward(graph) #set output node not important
        
        #step 3
        rate = 1e-2
        
        sgd_update(trainables, rate)
        
        loss += graph[-1].value
    if(i % 100 == 0):
        print("Epoch: {}, Loss: {:3f}".format(i, loss/steps_per_epoch))

Epoch: 0, Loss: 3.531043
Epoch: 100, Loss: 3.511125
Epoch: 200, Loss: 3.734476
Epoch: 300, Loss: 3.354633
Epoch: 400, Loss: 3.690993
Epoch: 500, Loss: 4.188894
Epoch: 600, Loss: 3.596938
Epoch: 700, Loss: 3.233360
Epoch: 800, Loss: 3.405211
Epoch: 900, Loss: 3.536451
Epoch: 1000, Loss: 3.688857
